doubleunion/arooo

app/models/user.rb
Fixes a mixed content warning on pages that display your gravatar if you're logged in (e.g. the application form page).
:warning: cc @lilliealbert I didn't run the tests 'cause postgres. I promise I feel bad about it.
=> Use https for gravatar urls

app/views/members/key_members/edit.html.haml
Fixing the issues at https://github.com/doubleunion/arooo/issues/214 - linking to the member handbook, noting the requirement to attend events, updating from keys to keycode + smartlock access.
=> Updating key member form

app/views/layouts/application.html.haml
This fixes some weirdness where other head tags were nested inside two meta tags, and makes the HTML valid-er. :sparkles:
=> Minor: Fix html meta tag structure

app/views/applications_mailer/approved.html.haml
We've switched to accepting applicants in a big batch, so brand-new members won't see any applications.
=> Update acceptance email

app/controllers/applications_controller.rb, app/views/applications/_show.html.haml, app/views/applications/edit.html.haml, db/migrate/20160615035631_add_pronoun_to_profiles.rb, db/schema.rb, spec/features/apply_to_du_spec.rb
Reverts doubleunion/arooo#241
There was a problem trying to save the Pronoun field when I tried on staging, and we forgot to put the field in the profiles so members can see them later. I would like to revert this change for now, as it needs some more tweaks!
=> Revert "Add Preferred Pronoun to Profile"

app/views/members/users/setup.html.haml
Inserted copy changes for the account setup page. ☀️ This resolves issue https://github.com/doubleunion/arooo/issues/256 filed by @carmiendo.
Updated setup information will be super useful for the incoming new batch of members.
=> Update copy on Account Setup page 👌🏽

app/views/admin/memberships/_members.html.haml
This resolves issue #253 to add user `email_for_google` to the admin memberships backend.
=> Add Member Google Email to Admin Manage Page

README.md
Make sure future contributors know about installing `ruby`, `rails`, and `bundler` from the RailsBridge Installfest Instructions. Many new contributors are unaware about `gem install bundler` and is a bit of a roadblock when setting up arooo on new machines.
=> Readme update to alert contributors about installing bundler 

Gemfile, Gemfile.lock
I changed the Gemfile so it uses the https version of that gem and gets rid of this warning:
> The git source `git://github.com/rails/actionpack-action_caching.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
=> Use https url for rails/actionpack-action_caching

config/initializers/constants.rb
QA: Nothing. Updates an unused constant, but keeps this repo in line with updates to doubleunion-dot-org.
=> Update mailing list constant

app/views/applications/edit.html.haml
We are changing "identify as a woman in a way that's significant to them" to "identify as a woman or non-binary person in a way that is significant to them" as per the large group discussion and the official vote by the board yesterday! 
Closes https://github.com/doubleunion/arooo/issues/281
=> Change gender criteria

Gemfile, Gemfile.lock, app/assets/javascripts/dues.js, app/controllers/members/dues_controller.rb, app/mailers/cancel_membership_mailer.rb, app/views/members/dues/show.html.haml, spec/controllers/members/dues_controller_spec.rb, spec/features/cancel_membership_spec.rb, spec/mailers/cancel_membership_mailer_spec.rb, spec/spec_helper.rb
Fixes stripe cancel button so that the member's dues are cancelled, and the membership coordinator receives an email informing them to remove the member from all mailing lists.
=> Fix stripe cancel button

Gemfile, Gemfile.lock, config/application.rb
This allows the new github pages site to fetch the members list from javascript.
=> Setup CORS for /public_members API

config/locales/en.yml
This would make this checkbox match the proposed new website language here: https://github.com/doubleunion/doubleunion-dot-org/pull/82
See doc with suggested edits here: https://docs.google.com/document/d/1Go3bDUJ0dLTSQ2FCv3GQkXiluzcPtA9R0PHjkUhxNN8/edit
=> Proposed update for gender language

Gemfile, Gemfile.lock
Changelog: https://github.com/stripe/stripe-ruby/blob/master/CHANGELOG.md
As far as I can tell there is no breaking change in major version 2->3
I ran: `bundle update stripe stripe-ruby-mock stripe_event`
> 3.0.0 - 2017-06-27
> #pay on invoice now takes params as well as opts
=> Update stripe gem

app/views/applications_mailer/approved.html.haml, config/initializers/constants.rb
I would prefer to make this configurable using something like `Configurable[:accepting_applications]` but I don't have much time right now for testing and I am sure that this will work.
=> Add new member orientation signup link to welcome email

Gemfile, Gemfile.lock, spec/factories.rb, spec/spec_helper.rb
Followed https://github.com/thoughtbot/factory_bot_rails/issues/247
This fixes https://github.com/doubleunion/arooo/issues/332
=> Update to factory bot

app/controllers/members/dues_controller.rb, app/models/user.rb
We weren't properly recording member's name and email in stripe which makes it difficult to properly identify who needs a donation receipt. We'll now keep this information up-to-date and I've run a backfill to populate the correct info for existing stripe customers.
=> Fix stripe name and email record

.gitignore, .travis.yml, Gemfile, Gemfile.lock, README.md, bin/rails, spec/spec_helper.rb
Add test coverage, fix dependencies, improve readme
Your bundle is locked to puma (3.12.3), but that version could not
be found in any of the sources listed in your Gemfile. If you
haven't changed sources, that means the author of puma (3.12.3) has
removed it. You'll need to update your bundle to a version other
than puma (3.12.3) that hasn't been removed in order to install.
https://github.com/colszowka/simplecov
Selenium::WebDriver::Error::SessionNotCreatedError:
session not created: This version of ChromeDriver only supports Chrome version 76
NOTICE: This gem is out of support as of 2019-03-31
Please use https://github.com/titusfortner/webdrivers instead.
See https://github.com/flavorjones/chromedriver-helper/issues/83 for details.
=> Add test coverage, fix dependencies, improve readme

README.md, config/application.example.yml
Adds some notes about a part of the dev environment setup that I found tricky. Also adds instructions on how to set up Google OAuth locally, and updates the `application.example.yml` file to include placeholders for variables related to Google OAuth. (This resolves issue https://github.com/doubleunion/arooo/issues/266.)
I also removed the top-level header of the README from the table of contents, because I like having a cleaner TOC with fewer levels of indentation.
No real code changes, so no tests.
Nope.
n/a
n/a
=> Update README with tricky bit during dev setup and local Google OAuth inst

Procfile
This PR adds a Procfile in order to:
* automatically run new migrations during a deploy
* enable us to do automated deploys to `staging` (which depends on automagically running migrations)
* better comply with Heroku's best practices
This resolves issues https://github.com/doubleunion/arooo/issues/428 and https://github.com/doubleunion/arooo/issues/408
Ran the server locally with this Procfile, using:
```
$ heroku local -f Procfile 
```
No.
n/a
After this PR is merged, I will enable, for `staging` only, the option to automatically deploy from `master`, after CI passes.
=> Add Procfile to enable automatically running migrations on deploy

Procfile
This PR fixes the Procfile added in https://github.com/doubleunion/arooo/pull/462 to pass Heroku's server port to our Rails server. Failure to do so prevents the server from starting up, as it is trying to bind to its default port, which is typically not available on Heroku.
From failed `staging` deploy with broken Procfile:
```
Jul 12 17:29:18 doubleunion-staging app/web.1 [2020-07-12 17:29:18] INFO  WEBrick 1.6.0
Jul 12 17:29:18 doubleunion-staging app/web.1 [2020-07-12 17:29:18] INFO  ruby 2.7.1 (2020-03-31) [x86_64-linux]
Jul 12 17:29:18 doubleunion-staging app/web.1 [2020-07-12 17:29:18] INFO  WEBrick::HTTPServer#start: pid=4 port=3000
Jul 12 17:30:13 doubleunion-staging heroku/web.1 Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
Jul 12 …
```
=> Pass PORT to server in Procfile

config/application.rb
Add `lib/` to eager-loaded paths, to make the code in this directory available in production and staging. This is a follow-up for the Rails upgrade in PR https://github.com/doubleunion/arooo/pull/441 -- apparently `/lib` is no longer eager-loaded by default by Rails.
Tested on `staging`, and locally.
No.
n/a
n/a
=> Add /lib to eager-loaded paths

Gemfile, Gemfile.lock, README.md, app/controllers/doorbell_controller.rb, config/routes.rb, spec/controllers/doorbell_controller_spec.rb
This PR moves the implementation of the doorbell endpoints from a separate app into Aroo. This is one of the steps in the work for https://github.com/doubleunion/arooo/issues/360 .
The code is largely untouched (including temporarily commented-out code and such), except for changes to adapt Sinatra code to Rails, and changing from using a keycode dictionary to querying our database.
Unittests. Light manual testing locally to verify that XML responses seem correct.
No.
n/a
Yes. Arooo now depends on having a Redis instance available to make the doorbell code work. I have already provisioned a free Heroku Redis on both our staging and production environments.
=> Port du-doorbell endpoint implementation into Aroo

app/views/members/users/index.html.haml, spec/features/members_home_spec.rb
As part of the work on https://github.com/doubleunion/arooo/issues/360, this PR adds a simple UI on the members home page (`/members`) to show them their current door code. The new UI has the following states:
* If the user is not a key member, nothing about the door code is shown.
* If the user is a key member, but the database has no door code for them, show them a message about contacting the membership coordinator. (This case should never happen, once we are done with everything, but added it just to be safe.)
* If the user is a key member and we have a door code, show it to them.
Feedback on tweaks to make the UI less janky are very welcome. 😉 
Tested on local server. Also tested in a spec.
No!
**Before change (and also for non-keymembers)**
**Key member with no door code**
**Key …
=> Add simple UI to show key members their door code

README.md, app/controllers/doorbell_controller.rb, app/models/door_code.rb, spec/controllers/doorbell_controller_spec.rb, spec/models/door_code_spec.rb
This PR updates the logic that checks keycodes to only allow door entry if the provided keycode is enabled.
This change also includes improvements to the documentation about the doorbell, including the changes that were previously in https://github.com/doubleunion/arooo/pull/470.
Specs.
No.
n/a
No.
=> Update the DoorBellController to only allow entry if a door code is enabled

app/controllers/admin/door_code_controller.rb, app/views/admin/memberships/_members.html.haml, config/routes.rb, lib/tasks/populate.rake, spec/controllers/admin/door_code_controller_spec.rb
As part of the migration of the doorbell code to Arooo (issue https://github.com/doubleunion/arooo/issues/360), this change gives admins a way to enable or disable members door codes. It is not the most elegant UI ever, but it works, and I think it is in a reasonably logical place in the app.
This PR also contains an unrelated change that improves the "realness" of the data generated by our `populate:users` rake task, which makes local development nicer.
Unit tests. Manual testing on local server.
No.
After:
=> Provide admin UI to view and enable/disable members' door codes

app/views/members/users/index.html.haml, spec/features/members_home_spec.rb
This change improves how we show their door code to members, so that they can tell if it is enabled or not (and thus, supposed to be working or not).
Specs. Manual testing on local server.
No.
After this change:
No.
=> Show members if their door code is enabled or disabled

app/controllers/admin/door_code_controller.rb, app/models/door_code.rb, app/views/admin/memberships/_members.html.haml, config/routes.rb, spec/controllers/admin/door_code_controller_spec.rb, spec/models/door_code_spec.rb
This PR adds the ability for an admin to generate a new unique door code for a member, through the "Manage Members" UI.
(This work is related to issue https://github.com/doubleunion/arooo/issues/360)
Specs. Local manual testing.
No.
No.
=> Provide a way for admins to generate a new door code for a member

app/models/user.rb, spec/models/user_spec.rb
As one of the finishing steps on the doorbell migration (tracked in https://github.com/doubleunion/arooo/issues/360), this PR sets a member's door code to be in state `enabled: false` if the member ceases to be a key member.
Unit tests.
No.
n/a
No.
=> Disable a member's door code when they are no longer a key member

app/controllers/doorbell_controller.rb, app/controllers/members/users_controller.rb, app/models/user.rb, app/views/members/users/edit.html.haml, db/migrate/20200823002316_add_pronounceable_name_to_users.rb, db/schema.rb, spec/controllers/doorbell_controller_spec.rb, spec/controllers/members/users_controller_spec.rb
This PR implements https://github.com/doubleunion/arooo/issues/477, with three pieces:
* adds a `pronounceable_name` to the `users` table
* adds `pronounceable_name` to the "Edit Profile" form, so that members can set their own pronounceable name
* changes the doorbell to use a member's pronounceable name, if there is one (fall back to the full name)
After adding this field to the `user`, I realized that we also have a `profile` table, where maybe this could have been added instead. Not sure if it matters much, but if you think that it makes more sense to have this on `profile`, let me know and I can change this PR to add `pronounceable_name` to `profile` instead of `user. 
Specs, and local testing.
Yes.
After the change (and a successful form submission), the "Edit Profile" page looks …
=> Add "pronounceable_name" field to User, make it editable, and have the doorbell use it

app/service_objects/account_setup_reminder.rb, spec/service_objects/account_setup_reminder_spec.rb
Handle nil processed_at and escape it
https://github.com/doubleunion/arooo/issues/463
rspec
no
n/a
no
=> Fix account setup reminder

config/initializers/stripe.rb
Fix for https://github.com/doubleunion/arooo/issues/492, to avoid developer Stripe API confusion in development.
Here is a screenshot from our Stripe dashboard to double-check that I set the correct API version:
(source https://dashboard.stripe.com/developers , logged in as Double Union account.)
The specs pass, the server starts up.
Nope.
N/a
No
=> Add explicit Stripe API version to Stripe initializer

Gemfile, Gemfile.lock, README.md
As suggested in https://github.com/doubleunion/arooo/issues/497, this PR removes some gems that seem to be unused. (Those gems might have facilitated development workflows for some devs, however. Unclear if/when these gems were last used by someone.)
n/a
No
n/a
No
=> Remove some unused development-only gems, to simplify setup

app/controllers/members/users_controller.rb, app/models/user.rb, app/views/members/users/index.html.haml
#449
Manually. 
1. Had no admins. Didn't see any admin section.
2. Made someone an admin. Saw an admin section as asked.
None.
before: 
after:
None.
=> Admins displayed on members home

app/controllers/members/dues_controller.rb, spec/controllers/members/dues_controller_spec.rb
Fixes https://github.com/doubleunion/arooo/issues/504
Controller spec
No
N/a
No
=> [fix] Avoid 500 status error in `members::dues#show` when customer does not have a plan

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, config/environments/production.rb, config/environments/staging.rb
Addresses #503 . Forces SSL in production/staging through rails configuration, removing custom logic to do that from the application controller.
Could be deployed to staging to ensure it works as expected.
No
N/a
Not apart from the included in the PR.
=> Force SSL using rails configuration for production/staging

app/controllers/doorbell_controller.rb, spec/controllers/doorbell_controller_spec.rb
Closes #475 
Raise error when no doorcode is provided in the param body as it would previously throw undefined method `strip' for nil:NilClass and this way it returns a more graceful error me ssage. Addded context for when "without a doorcode" it "should raise a NoMethodError with a clearer error message"
Within `spec/controllers/doorbell_controller_spec.rb` within the sms block with context of "without a doorcode". 
Nope 🙂
If there is any feedback or anything that can be improved please let me know! Thanks for letting me work on this! 🎉
=> #475 Add error for when doorbell/sms endpoint is called without a doorcode

app/views/applications/edit.html.haml
Try to ensure we’re clear in the application process that application content will be visible to all current DU members. This is because some new members have been surprised to find out that all current members were able to view their applications during the voting process. We want to ensure that applicants are appropriately informed about what we do with their information.
It's just a text change, no test changes needed.
No
No
=> Clarify visibility of application

Gemfile, Gemfile.lock
Remove `execjs` gem from our `development` dependencies, because I can't find any references to it in our code, and it is giving setup troubles to a contributor.
The specs pass.
No.
n/a
no!
=> Remove development-only gem execjs, which seems unused

app/controllers/applications_controller.rb, app/models/profile.rb, app/views/applications/_show.html.haml, app/views/applications/edit.html.haml, db/migrate/20201124040111_add_attendance_to_profile.rb, db/schema.rb, spec/features/apply_to_du_spec.rb
This updates the text of our application questions to [our revised questions](https://docs.google.com/document/d/1PZzJFyXQCgi_KQyxm8_1cegp4Ep7AX3xNl40v2Fo-XI/edit#), including removing some of the old questions and adding a new one ("Have you been to DU events or met DU members?"). The underlying goal is to lower the stress of being an applicant by removing questions that we don't need to make a decision about an application.
This is only a content change, and it needs some engineering work - I added a new "attendance" element because of the new question, but that needs to become part of the code and databases. That still seemed like a better idea than awkwardly reusing one of the elements I removed.
I also removed the "Blog URL" field because that seems a bit outdated/weird (if a person …
=> Content update for application questions

app/controllers/applications_controller.rb, spec/controllers/applications_controller_spec.rb
This PR addresses https://github.com/doubleunion/arooo/issues/317 in two ways:
* When an applicant submits an application that is already submitted (e.g. they submitted in a different tab, or they clicked the "Submit" button twice), show a notice confirming that the application is already submitted. Don't show any errors.
* Report the error message of any error, not just the invalid state transition issues. If something really unexpected goes wrong, the error message might not be very applicant-friendly, but it might help us debug the issue if they report the problem to us. (There are some unexplained bug reports in https://github.com/doubleunion/arooo/issues/317)
My intent is to make any future application submissions easier to diagnose, as well as to make the "double submission" …
=> Handle more gracefully attempts to double-submit an application and rescue + report all errors

app/controllers/members/applications_controller.rb, app/models/user.rb, spec/features/sponsorship_spec.rb
To address issue https://github.com/doubleunion/arooo/issues/252, this PR adds a "notice" (not an error) that says "You are already sponsoring this application!", shown to a member who is already a sponsor and tries to sponsor the same application again.
Added a test case into the appropriate spec.
No.
With this change, after submitting the "i want to sponsor" form for a second time:
No.
=> Add more meaningful message when a sponsor tries to sponsor the same application again

app/views/new_members_mailer/fourteen_day_reminder.html.haml, app/views/new_members_mailer/seven_day_reminder.html.haml, app/views/new_members_mailer/three_day_reminder.html.haml, app/views/new_members_mailer/twenty_one_day_reminder.html.haml
Currently if a new member applies for a dues scholarship and is waiting to hear back about it, the Arooo system doesn't know that they're waiting on something (they look like they just haven't finished setting up their account), so they keep getting confusing email reminders about setting up their account.
Until we can come up with a better fix, this is a text change to tell people it's ok to ignore the emails if they're waiting on a scholarship application.
This addresses the main issue described at https://github.com/doubleunion/arooo/issues/339
I don't know
No
I don't have screenshots - I worked on it locally.
No
=> Add notes about scholarship processing to member setup email reminders

app/views/members/users/_bookmarks.html.haml
This updates the "Bookmarks for Members" list on the DU internal app homepage to add context that should resolve a couple of common user confusions: https://github.com/doubleunion/arooo/issues/222 + https://github.com/doubleunion/arooo/issues/215. I also removed the "Bookmarks for Key Members" section because it was just another link to the Member Handbook.
I imagine it doesn't need or have any specific tests, because it's just a set of text changes.
No
This is the "before" view:
No
=> Update "Bookmarks for Members" to help members navigate DU tools

app/views/layouts/_navigation.html.haml, config/initializers/constants.rb
This adds Instagram and Facebook links to the header bar, to make them easier to access for members. They're probably still not totally visible and easy to find, but at least it's better! This closes https://github.com/doubleunion/arooo/issues/417.
I don't think there are tests for this.
No.
Before:
After:
I changed the constants file to reflect the structure that was already in place.
=> Add Instagram and Facebook links to header

app/views/dues_mailer/failed.html.haml, app/views/layouts/_member_nav.html.haml, app/views/members/dues/show.html.haml, app/views/members/users/setup.html.haml, spec/controllers/members/dues_controller_spec.rb, spec/features/cancel_membership_spec.rb
This renames the "Manage Dues" page to "Manage Membership" because the page allows you to do multiple things related to managing your membership. It also adds a table of contents to the top of the page, because people frequently miss that there's a "cancel your membership" option at the bottom of the page.
This closes https://github.com/doubleunion/arooo/issues/514
I attempted to update the tests to match the change.
No
After:
No
=> Rename "Manage Dues" to "Manage Membership"

app/views/members/users/edit.html.haml, app/views/members/users/index.html.haml, spec/features/members_home_spec.rb
These changes should help members understand:
* What a Gravatar is (if they've never heard of one)
* How to fill out the pronounceable-name field
* How and why to update their Google-friendly email address
* That it's ok if they don't have a door code if they don't need one
I also corrected the membership coordinator email address from .com to .org by using the constant for it.
This closes https://github.com/doubleunion/arooo/issues/530 and https://github.com/doubleunion/arooo/issues/531.
I attempted to update the relevant test as well.
No
After, edit profile page:
After, member homepage:
No
=> Help members understand how to edit their profile information

Gemfile.lock
Updates `brakeman` to the latest version, so that our continuous build checks pass again.
No changes to code or the app. (Brakeman is a static security analysis tool.)
=> Update brakeman to latest version

app/views/applications_mailer/approved.html.haml, config/configurable.yml, config/initializers/constants.rb, spec/controllers/admin_controller_spec.rb, spec/mailers/applications_mailer_spec.rb, spec/models/application_spec.rb
Make the orientation link configurable, so that people don't have to edit the constants when there's a new orientation signup link. Also remove DU's old address from the welcome email (this will need to be updated when DU has a physical space again - noted at https://github.com/doubleunion/arooo/issues/538).
This closes https://github.com/doubleunion/arooo/issues/336. Syd and I worked on this together.
Not sure
No
I don't think so.
=> Make orientation configurable + remove address from welcome email

app/views/admin/applications.html.haml
This is a followup on https://github.com/doubleunion/arooo/pull/539. It adds a note telling the person accepting applications to configure the orientation signup link.
It's not, but it's just a text change, so that should be ok.
No
After:
No
=> Tell the membership coordinator that the orientation link must be configured

app/controllers/members/key_members_controller.rb, app/mailers/member_status_mailer.rb, config/initializers/constants.rb, spec/mailers/member_status_mailer_spec.rb
At the original DU space, we had a role that managed actual physical keys (chatelaine / key wrangler), with their own email address. We don't have a separate role for that anymore, so the key email address is redundant. I removed it from all the places it still existed in the code.
I also removed a few other constants that aren't used in the code anywhere.
Not sure
No
None
This updates the constants file.
=> Remove old constants, including keys email that we don't use

Gemfile, Gemfile.lock
Resolves open dependabot alert due to advisory https://github.com/advisories/GHSA-vr8q-g5c7-m54m
=> Update nokogiri version according to advisory CVE-2020-26247

Gemfile.lock, app/controllers/sessions_controller.rb, app/views/applications/show.html.haml, app/views/sessions/login.html.haml, spec/controllers/sessions_controller_spec.rb
Resolves https://github.com/doubleunion/arooo/issues/529
This PR resolves https://github.com/doubleunion/arooo/issues/529 and contains two changes:
* A logged-in applicant is shown one of two things on the '/' page:
* if applications are open, a link to edit their application
* if applications are closed, a notice to that effect, and a link to the website page that links to the announcement mailing list
* When you are viewing (not editing) your own application, changes the header to say "Your application" (instead of "View application").
(Initially I made the homepage redirect an applicant automatically to edit their application, but this turns out to be a Bad Idea in the case when applications are closed, because when applications are closed the "edit your application" page redirects you …
=> Show logged-in applicants link to edit their application on the homepage

app/controllers/members/applications_controller.rb, app/views/members/applications/index.html.haml, spec/controllers/members/applications_controller_spec.rb
Resolves https://github.com/doubleunion/arooo/issues/318
Divides the list of applicant emails on the applicant index page into applicants with sponsors and applicants with no sponsors, so that each list can be easily contacted separately, if need be.
Specs and local manual tests.
No.
No.
After these changes:
=> Display applicant emails in two separate lists: with sponsors and no sponsors

Gemfile, Gemfile.lock, app/controllers/admin/memberships_controller.rb, config/brakeman.ignore, spec/controllers/admin/memberships_controller_spec.rb
This updates us to the latest Brakeman version, which is required as a safety measure by our CI configuration. This should fix the [CI failure](https://travis-ci.org/github/doubleunion/arooo/builds/759914734) that happened on https://github.com/doubleunion/arooo/pull/566
=> Update Brakeman to the latest version

app/views/sessions/login.html.haml
Resolves https://github.com/doubleunion/arooo/issues/564
Switches the order in our copy of "GitHub and Google" to match the order of the respective buttons.
Local server visual inspection. See screenshots below.
No
No
Before:
After:
=> Update order of GitHub and Google in login page copy to match order of login buttons

app/models/application.rb, spec/controllers/applications_controller_spec.rb, spec/factories.rb, spec/features/apply_to_du_spec.rb, spec/models/comment_spec.rb, spec/models/sponsorship_spec.rb, spec/models/vote_spec.rb
Resolves https://github.com/doubleunion/arooo/issues/565
Adds a validation step during submission to ensure that answers to the application questions are not empty. If a field is missing, the user is shown an error message at the top of the page letting them know which field is missing.
Specs and manual testing.
No.
No.
With this change, here are screenshots of the error states:
=> Require an application to have answers to required questions before it can be submitted

app/models/application.rb, config/configurable.yml, spec/models/application_spec.rb
This PR resolves https://github.com/doubleunion/arooo/issues/572 by adding a configuration boolean, accessible to site admins, that can be used to turn off sending of "new application submitted" emails to all members.
This can be used for testing the application flow without spamming the membership.
Added test case.
No.
No.
New version of the "Config" section in the app:
(The Configurable gem doesn't seem to let us order those fields in the form, so it looks a little meh, but it is functional.)
=> Add Configurable field to turn off new application emails (useful for testing the new application flow)

Gemfile.lock
Resolves the recent Rails install/build issue caused by a yanked `mimemagic` version (see https://github.com/mimemagicrb/mimemagic/issues/98 and
=> Update mimemagic to available version

app/models/user.rb, app/views/admin/door_codes/_form.html.erb
For https://github.com/doubleunion/arooo/issues/594, usability improvements to the user drop-down in the door code edit form:
* only show current members (of any kind)
* also show email address (in case a member has no name or a partial name in the database)
* sort alphabetically by name
=> Only show current members in door code edit dropdown, show email, and sort alphabetically

app/models/door_code.rb
As part of https://github.com/doubleunion/arooo/issues/594, improve naming of status for disallowed codes.
=> Rename 'blacklisted' status to 'denylisted'

app/views/admin/door_codes/_status_legend.html.erb, app/views/admin/door_codes/edit.html.erb, app/views/admin/door_codes/index.html.erb, app/views/admin/door_codes/new.html.erb
For https://github.com/doubleunion/arooo/issues/594, add a legend element that explains the meaning of the door code statuses. We can workshop the wording of the text in follow-up changes.
=> Add a simple legend explaining the meaning of the door code statuses

app/controllers/admin/door_codes_controller.rb, app/views/admin/door_codes/_codes_table.html.erb, app/views/admin/door_codes/_status_legend.html.erb, app/views/admin/door_codes/index.html.erb
For https://github.com/doubleunion/arooo/issues/594, group door codes in the index table by status, and update wording in status legend. Also sorted the codes alphabetically by name of the person they are assigned to.
=> Group door codes by status in index table

app/models/door_code.rb, app/models/user.rb, app/views/members/users/index.html.haml, spec/factories.rb, spec/models/door_code_spec.rb, spec/models/user_spec.rb
For https://github.com/doubleunion/arooo/issues/594, grab-bag of improvements around door codes:
* improve how we show a member their own door code on the Members home page
* ensure that we reject door codes that aren't numerical or that aren't at least 6 digits long
=> Improve display of own door code to members, reject non-numerical or too-short door codes

app/views/applications_mailer/approved.html.haml
Resolves #538
When we didn't have a physical space, I removed related information from the new-member email, since I thought we might reopen membership while virtual. We didn't, and we have a space again, so I added the main info back.
=> Add back info about orientation and key membership

app/views/members/users/index.html.haml
None
When a person goes to DU and enters their key code, they need to press * on the keypad to inform the lock that they have completed entering their code. This adds that to the homepage display of the code, to tell people to press it as part of their code.
I didn't try it locally. I'm hoping that the * is treated as a literal * and not as a code thing. :D
=> Add asterisk at end of door code display

app/controllers/admin/door_codes_controller.rb, app/models/door_code.rb, app/views/admin/door_codes/_codes_table.html.erb, app/views/admin/door_codes/_form.html.erb, db/migrate/20220129183750_add_index_to_door_code.rb, db/schema.rb, spec/factories.rb, spec/models/door_code_spec.rb
Addresses https://github.com/doubleunion/arooo/issues/609
Adds an integer column, `index_number` to Door Codes, and exposes it in create, edit and show UIs. This attribute is for tracking the "index number" for a code in our lock, which is needed in order to administrate the codes.
The `index_number` is not required but, if set, it is validated to be unique.
Unit tests and manual local testing.
Yes.
No.
=> Add `index_number` to Door Code

app/views/members/users/index.html.haml
Addresses https://github.com/doubleunion/arooo/issues/605
Makes sure that a member who is not a key-member always sees the "Become a key member" button on the members' home, even if they already have a door code assigned.
Manual testing locally.
No.
No.
**For a member with no door code**
**For a key member that has no assigned door code**
**Edge case that shouldn't happen: for a member who has a door code but is not a key member**
**For a key member that has a door code**
=> Make sure that "Become key member" button appears for non-key-members

Gemfile, Gemfile.lock
Cleaning up some dependencies to make upgrades easier in the future.
=> Remove no longer necessary direct dependency on BigDecimal

Gemfile, Gemfile.lock, config/environments/production.rb, config/environments/staging.rb
This change addresses https://github.com/doubleunion/arooo/issues/676 : a recent gem upgrade for `aws-sdk-rails` changed the name of the email "delivery method" it provides, but we didn't update our configuration to match. This PR fixes this.
=> [BUG] Fix mailer configuration to match new version of aws-sdk-rails

app/views/applications/_show.html.haml, app/views/applications/edit.html.haml
Cleanup in the files that the change for #487 touches.
* On the application edit page, the "required" marking on fields is not enclosed in parentheses, but the "(optional)" marking is in parentheses. This PR changes "required" to "(required)" for consistency.
* On the application show page, not all fields are marked as "required" or "optional". This PR marks all of the fields.
* The explanation for why we ask for pronouns is phrased differently on the edit and show pages. This PR updates the two pages to use the same language.
Locally -- only text changes
No
No
Edit page:
Show page:
Edit page:
Show page:
=> Use consistent language and punctuation on application pages.

app/controllers/applications_controller.rb, app/views/applications/_show.html.haml, app/views/applications/edit.html.haml, spec/controllers/applications_controller_spec.rb
#487 
Currently, after a new member is accepted, they need to add a Google-friendly email address that we can use for sharing the DU Google Drive and Google Calendar. The membership coordinators often need to remind people to add Google-friendly emails.
This PR moves adding a Google-friendly email into the application process. The Google-friendly email is optional as suggested by Britta in issue #487, in case someone wants to join without a Google address.
This PR lets people fill in this field manually. Britta also suggested in issue #487 that we could try to fill in the Google-friendly email automatically when people log into the DU app with Google. I will look into that separately. We could also consider setting the Google-friendly email to the contact email if it ends in "@gmail.com" …
=> Add Google account email to application edit and show pages.

app/controllers/sessions_controller.rb, spec/controllers/sessions_controller_spec.rb
Resolves #487.
I added a Google account email to the application form in pull #696.
This PR sets the new Google account email field automatically if a new applicant logs in with Google OAuth, as Britta suggested in issue #487.
Manually and with specs.
No (the email_for_google field already exists and is set in other places in the app)
No
1. I have to enter a contact email to get to the application page:
2. On the application page, "Google account email" is already filled in, to the email address I used to log in with Google:
3. email_for_google is already set in the database from the OAuth login, before I save the application:
1. I have to enter a contact email to get to the application page:
2. On the application page, "Google account email" is not set yet, as expected since I logged in …
=> Set Google account email automatically when a new applicant logs in with Google OAuth.

app/assets/stylesheets/membership_application.scss, app/assets/stylesheets/utilities.scss, app/views/applications/edit.html.haml
#562
Move the block of social media links in the application form to the bottom of the form, as suggested in https://github.com/doubleunion/arooo/issues/562.
I also removed the nested-table style from the stylesheet for this page. It was only used for the nested table that contains the checkboxes at the end of the form. I think the nested table with the checkboxes looks slightly better without this style (the checkboxes are better aligned with the other form items -- see screenshots). Additionally, the new nested table for the social media links does not look good with the nested-table style, and it would be confusing to have a nested-table style that is used for one of these nested tables but not the other.
Locally -- UI changes only.
No
No
Social media links at the top of the …
=> Move block of social media links to the bottom of the application form.

app/views/applications/edit.html.haml
#562 
As suggested in issue #562, this PR:
* Removes the feature that lets applicants preview their unsubmitted applications
* Removes the explanatory text about using markdown to format an application
* Clarifies application visibility -- applications are visible to all current DU members while they are open, then they are no longer visible once they have been accepted or rejected.
Locally -- only UI changes.
No
No
Top of page (preview link and text about markdown removed; application visibility clarified):
Bottom of page (preview link removed):
Once an application is submitted, you can still use "View application" to see how the application will look to voting members. This behavior existed before and I did not remove it. We can remove it if it's confusing / not useful.
"View …
=> Remove feature for previewing unsubmitted applications and clarify intro text in application form.

app/views/applications/edit.html.haml, config/initializers/constants.rb
#562
As suggested in github.com/doubleunion/arooo/issues/562, this PR updates the checkboxes at the end of the application to:
* Ask applicants to read and acknowledge the base assumptions
* Link directly to the "Membership Benefits and Responsibilities" section on the public website, instead of the top of the membership page
* Clarify that applicants need to read the base assumptions and membership benefits and responsibilities, and be generally ok with them, but it's fine if they don't understand them completely yet.
Locally -- UI changes only.
No
I think so but am not certain (not familiar with Rails). This change adds a value to config/initializers/constants.rb, and I think this counts as a configuration change that will require restarting the server.
=> Update checkbox about assumptions, benefits, and responsibilities in application form.

app/models/user.rb, spec/models/user_spec.rb
None
If transitioning from key_member to voting_member the key_code is not removed.
Added a test
No
No
=> bugfix: for changing from key_member to voting_member removed key code

app/helpers/application_helper.rb
None
When I paste links to DU app pages into Slack, the automatic description is outdated. I updated it.
I don't know
None
None
=> Update outdated description

app/views/members/users/_bookmarks.html.haml
Didn't file an issue.
Change the handbook link on members homepage to the key code orientation link.
Discussed during the membership committee meeting on 2/1/23. The handbook is very long, and probably what most people need to know is how to get into the DU space. The key code orientation slide deck explains how to get into the DU space more concisely.
Locally -- screenshot below.
No unit tests needed because this is just a text change.
No
No
I tried the new "Key code orientation" link to make sure it goes to the right place.
=> Change handbook link on members homepage to key code orientation link.

app/views/admin/applications.html.haml, app/views/applications_mailer/approved.html.haml, config/configurable.yml, spec/mailers/applications_mailer_spec.rb, spec/models/application_spec.rb
None -- discussed during the virtual membership committee meeting today, and did not file an issue.
We have a rolling application process now, so we won't do one batch of orientations all at once that all new members should sign up for. I think it would be hard to keep an orientation signup page up to date as new members apply throughout the year, and it would probably be easier to have the membership coordinator handle scheduling orientations for new members as needed.
Unit tests.
Also ran the code in my local environment, but I think the local environment doesn't actually send emails. When I approve an application, the server logs that it's sending an email and logs the contents of the email to the console (screenshot below), but no email is actually sent.
No
No
Screenshot of the email …
=> Remove configurable for orientation signup link.

app/views/applications_mailer/confirmation.html.haml
None
We aren't really using our Twitter for event announcements much anymore, so I replaced that link with Instagram (where we post announcements more often).
=> Replace Twitter with Instagram in new member email
