doubleunion/arooo

app/views/members/applications/index.html.haml
app/views/members/applications/show.html.haml

Aw yeah, I finally implemented https://github.com/doubleunion/arooo/issues/223 !!!!
Thanks @lilliealbert for helping me figure this out!

Add information about policies to application pages

---

app/views/member_status_mailer/new_key_member.html.haml

It's easier for key coordinators if people proactively reach out.

Minimum viable update to clarify getting keycodes

---

app/controllers/applications_controller.rb
app/views/applications/_show.html.haml
app/views/applications/edit.html.haml
db/migrate/20160615035631_add_pronoun_to_profiles.rb
db/schema.rb
spec/features/apply_to_du_spec.rb

Fixes  Issue #209
@mathildemouw and I paired!

Add Preferred Pronoun to Profile

---

README.md

Adding a note about the #du-app channel for members; updating other bits; linking to the announcement blog post that includes a couple screenshots. (So this closes https://github.com/doubleunion/arooo/issues/219 !)

Updating readme with tips

---

app/views/members/dues/show.html.haml

This is a text change to close https://github.com/doubleunion/arooo/issues/239 - since it's confused a few people in the past.

Explaining Stripe dues subscription automatic pro-rating

---

app/views/applications_mailer/notify_members.html.haml

Closes https://github.com/doubleunion/arooo/issues/240

Send only first line and link in new application email

---

app/views/applications_mailer/approved.html.haml
app/views/applications_mailer/member_access.html.haml

These changes mostly just clarify the welcome emails to account for the new mailing list structure and other suggestions from the voting members from our meeting today.

Update new member emails to prepare for their arrival!

---

app/assets/javascripts/dues.js
app/assets/stylesheets/admin.css.scss
app/assets/stylesheets/utilities.css.scss
app/controllers/members/dues_controller.rb
app/views/layouts/_messages.html.haml
app/views/members/dues/show.html.haml
config/routes.rb
spec/controllers/members/dues_controller_spec.rb

Just doing some cleanup on the spec in https://github.com/doubleunion/arooo/pull/248!

Cancel dues cleanup

---

README.md

Addresses https://github.com/doubleunion/arooo/issues/267

Update Readme to explain postgres installation

---

README.md

Add more instructions for running postgres (`rake db:create` kept failing on me until I ran this)

Add more postgres instructions

---

Gemfile
Gemfile.lock
README.md
app/controllers/members/comments_controller.rb
app/views/members/comments/index.html.haml
spec/features/view_comments_spec.rb

Add date to comments page, remove incorrect sorting

---

Gemfile
Gemfile.lock
app/helpers/stripe_event_helper.rb
spec/controllers/members/dues_controller_spec.rb
spec/helpers/stripe_event_helper_spec.rb

This fixes issue #315 
In addition to the changes in this PR I ran `bundle update rest-client stripe stripe_event stripe-ruby-mock` and then used irb and the below script to get (my own) user data from Stripe to prove that this works
```(ruby)
require 'stripe'
stripe_customer_id = '[redacted]'
Stripe.api_key = '[redacted]'
customer = Stripe::Customer.retrieve(stripe_customer_id)
```

Fix stripe integration

---

Gemfile
Gemfile.lock
app/models/authentication.rb
spec/models/authentication_spec.rb

Making progress! Stripe 2.12 was released in 2017 :) https://rubygems.org/gems/stripe/versions

More gem updates including stripe gem update 2.5 -> 2.12

---

config/initializers/stripe.rb

This should fix #315 webhook issue

Set StripeEvent.signing_secret so that webhooks will work

---

app/views/members/dues/_form.html.haml
app/views/members/dues/show.html.haml

Add more dues levels, adjust the default to reflect the average giving, and add an explanation of DUs financial model on the dues signup page.

---

app/views/admin/new_members.html.haml

I just followed these instructions and I think they can be improved

Making member setup instructions more clear

---

app/views/applications/edit.html.haml
config/locales/en.yml
config/locales/es.yml
config/locales/it.yml

As anticipated to Carmen, we are finally pushing the Italian translations to Aroo.
We added the possibility to change the language in the application page in the lightest way possible.
Cheers,
Carlo

Italian translation

---

README.md

https://groups.google.com/a/doubleunion.org/forum/#!forum/public-du-code

add mailing list

---

README.md

This is for https://github.com/doubleunion/arooo/issues/381

adhere to bugsnag OSS program requirements

---

app/mailers/dues_mailer.rb
app/views/dues_mailer/scholarship_requested.html.haml
spec/controllers/members/dues_controller_spec.rb

I'm not sure that this works, add a test before merging!

Add user and text to scholarship email

---

README.md

When you are making a pull request, please fill this out. It is ok if the answer to a question is "none" or "I don't know", the maintainers will be happy to help you out!
Only fixing Readme file.
Because link is wrong.
By my browser.
No.
I don't think it's necessary.
No.

Fixed Bugsnag link in Readme

---

Dockerfile
README.md
config/database.docker.yml
docker-compose.yml

[ISSUE 401](https://github.com/doubleunion/arooo/issues/401)
Adds a docker setup for development. Makes setting up development env easier.
Refer to Readme file on Docker setup
no
You'd have to change your DB settings and point the host to the Docker service `db`

Adds development Docker setup

---

.github/bug_report.md
.github/feature_request.md

Add Issue Template

---

README.md

This adds a note to the README, and a table of contents (to make it easier to navigate). (PR also includes whitespace changes, courtesy of my editor configuration, sorry.)
No code changes, so no tests. 😸 
Nope.
Not applicable!
No.

Add table of contents and note about state machine gem to README

---

app/models/door_code.rb
app/models/user.rb
db/migrate/20200709004913_create_door_codes.rb
db/schema.rb
spec/factories.rb
spec/models/door_code_spec.rb
spec/models/user_spec.rb

This PR depends on https://github.com/doubleunion/arooo/pull/441 , and can't be merged until that change is merged.
This PR adds a a `DoorCode` model. This is the first step in the work for https://github.com/doubleunion/arooo/issues/360
See specs.
Yes! That's the point!
No app or UI changes yet, screenshots not relevant.
Nope.

Add door_codes table and model

---

README.md

Updates README with notes about latest changes to the deployment process (related to issues https://github.com/doubleunion/arooo/issues/428 and https://github.com/doubleunion/arooo/issues/408)
n/a
n/a
n/a
No.

Add notes on automated deploys and database migrations to README

---

lib/tasks/populate.rake

fix https://github.com/doubleunion/arooo/issues/495
locally
no
no
no

save user after changing attribute

---

config/initializers/constants.rb

Remove unused constant from constants initializer related to this issue https://github.com/doubleunion/arooo/issues/431 
the code needs no test
No
-
No

remove CONTACT_EMAIL from constants

---

Gemfile
Gemfile.lock

Upgrades puma from 3 to 4 ( issue #429 )
Existing feature specs in place will test the upgrade
No
N/a
No

[bundle] Upgrade puma to latest 4.*.*

---

app/controllers/admin/memberships_controller.rb

Addresses #476 
Existing regression controller specs
No
N/a
No

[fix] Include door code in users query to avoid N+1 DB consultation

---

.travis.yml
Gemfile
Gemfile.lock
app/controllers/admin/memberships_controller.rb
app/models/comment.rb
app/models/sponsorship.rb

Add brakeman

---

README.md

This PR attempts to capture various issues that came up today as folks were setting up their local Arooo environment for work on membership application stuff.
This updates the README.
n/a
nope!
n/a
no, ma'am

Add various pieces of documentation and clarification to setup instructions

---

README.md

Updates the README to have more information about trying to set up Arooo on Ubuntu, gleaned during a pairing session with @sydshafer

Update README with notes from trying to set up Arooo on Ubuntu

---

README.md

None
I removed the outdated info for reporting a security vulnerability and directed viewers to our security.md, I added a bit of context for non-members, etc
No tests needed

Readme maintenance

---

app/views/applications/_show.html.haml
app/views/applications/edit.html.haml

None; this is a followup on https://github.com/doubleunion/arooo/pull/521
This updates the application question content for "tell us about your feminism", based on discussion last week with major input from @ncala (thank you!). It's an effort to make the language more approachable and specific for a wider range of potential applicants.
I don't think any tests need to be updated for this, because it just changes the content.
No
No
This is the updated question and description:

Update application questions based on working session last week

---

.github/workflows/ruby_lint.yml
.github/workflows/security.yml

none
Use new main branch for builds
Because we want to test the branch that is being changed
github actions
no
no
n/a

Use new main branch for builds

---

Gemfile
Gemfile.lock

none
update pg so we can be up to date 
launch server
no
no

Update gem pg for postgres integration

---

README.md

None
I was looking for the command to run the application in the readme, and it took me a second to realize the dev instructions were in the contributing guide, so I added a little bit more of a hint.

Make more clear how to find the setup/run info

---

app/views/members/dues/show.html.haml

None
For members who are part of companies with donation matching programs, this gives a tip about how to set up your matching! This can help DU get more money. :)
No tests, just a text change. It should be reviewed by Sophia because she knows the most about helping people set up matching.

Add corporate matching info to dues setup info

---

app/views/applications/edit.html.haml

None
This updates our application questions based on review last week, including contributions from @sylphiae. I also tried expanding the question area for the answers, based on our review of UX.
Not applicable

Update question text based on last week's review

---

app/views/members/key_members/edit.html.haml

https://github.com/doubleunion/arooo/issues/595
Updates language for key membership form!

Draft updates to key member form

---

README.md

Add CI badges to readme

---

app/views/admin/door_codes/index.html.erb

Resolves #614
This will help board members and membership coordinators add and remove user codes.
No testing needed, just text changes.

Basic instructions for code management

---

Gemfile
Gemfile.lock
app/controllers/admin/configurables_controller.rb
config/routes.rb

Makes us less behind. 😅 
Also removed some unused routes that were meant for the old doorbell.

Update gem configurable_engine

---

app/views/members/dues/_form.html.haml
app/views/members/users/setup.html.haml

None
Hopefully bump up average dues paid by new members
I did not test this code locally. I'm not sure how the table will look.
No

Adjust default dues

---

app/views/members/dues/show.html.haml
app/views/members/users/setup.html.haml

None
Make the suggested dues table more readable on the setup page, and add a matching table to the "manage membership" page.
I didn't add any tests
No
No

Improve dues table & add it to "manage membership" page

---

app/views/members/dues/show.html.haml
app/views/members/users/setup.html.haml

None
This simplifies the suggested dues scale and adjusts the higher end of it, to what seemed to make more sense to me (and another member I casually chatted with about it).
It's not.

Simplify dues scale, adjust higher end of it

---

app/views/applications/edit.html.haml

None
Try to reformat the multi-question "tell us about your feminism" question into a "pick one" list, to make it a little less overwhelming for applicants.
I haven't tested it, and I don't have a good way to preview this locally, so it might look weird? But it may be fine.
No

Adjust formatting of feminism question

---

app/views/members/dues/show.html.haml

Didn't file an issue
Add a sentence to explain how members can update their card on file with Stripe without changing their dues amount.
A member reached out to the membership@ email address asking how to update their card without changing the dues amount. I think it's a bit unclear in the app -- it looks like the "Update Dues" button is only for changing the dues amount.
Locally -- screenshot below.
No unit tests needed because this is just a text change.
No
No

Explain how to update card on file without changing dues amount.

---

README.md

An update to our README, motivated by our recent Quest to Find Sent Emails 🛡️⚔️.

Update README notes on email sending, and environment variable configuration

---

README.md

Simple text update to match our current configuration.
None! Observed by a guest.

Update "master" to "main" in readme

---

app/views/member_status_mailer/new_key_member.html.haml

None
* Remove outdated references to keycode and smartlock access.
* Adjusted to accommodate that most people seeing this email have just completed an orientation.
I don't know
No
No
N/A

Update automated email for new key members
